LOCAL_PATH := device/samsung/j13g

USE_CAMERA_STUB := true

# Define Headers
TARGET_SPECIFIC_HEADER_PATH := device/samsung/j13g/include


# Assert
TARGET_OTA_ASSERT_DEVICE := j13g,J100H,SM-J100H

# inherit from the proprietary version
-include vendor/samsung/j13g/BoardConfigVendor.mk

#Platform
TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := sc7715
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := sc7715

BOARD_KERNEL_CMDLINE := console=ttyS1,115200n8
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_TAGS_OFFSET := 0x00000100
BOARD_MKBOOTIMG_ARGS := --dt device/samsung/j13g/dt.img

TARGET_KERNEL_SOURCE := kernel/samsung/j13g
TARGET_KERNEL_CONFIG := j13g-dt_hw01_defconfig

#Use file-based OTA instead
BLOCK_BASED_OTA := false

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1085440000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_FLASH_BLOCK_SIZE := 131072

# Recovery
TARGET_RECOVERY_FSTAB := $(LOCAL_PATH)/rootdir/fstab.sc8830
